# Generated by Django 5.2.9 on 2026-01-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_reminder_last_triggered_reminder_is_sent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="todo",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
